Clean/Gadgets/Addition8Full.lean
Clean/Utils/Field.lean

Add a gadget that enforces the relation of an 8-bit full adder, with two boolean flags: an input carry and an output carry. Maybe it will not be used in Add32, but IMO is a nice gadget to have in any case.

Add 8 bit full adder gadget

---

Clean/Tables/Fibonacci.lean
Clean/Utils/Tactics.lean

After experimenting with metaprogramming (and after countless crashes of the Lean core while testing xD) I wrote this simple `specialize_auto` tactic, which takes in input one hypothesis `t` in the form `h1 -> h2 -> ... -> hn -> t'` and tries to find matching terms `h1`, `h2`, ..., `hn` in the current context and specializes the initial term as far as possible.
Maybe it will not be necessary in the new circuit formulation, but it might be useful as a template for other similar tactics.

Add specialize_auto tactic

---

Clean/Circuit/Circuit.lean
Clean/Utils/Vector.lean

* changes the subcircuit operation to have notions of assumptions/inputs/outputs, and require both a `soundness` and `completeness` statement.
* use a subcircuit's `completeness` when proving completeness of a parent circuit
* confirm that the completeness proof of `add8_wrapped` is now trivial

[Circuit monad] Completeness composition

---

Clean/Circuit/Circuit.lean
Clean/Circuit/Provable.lean
Clean/Utils/Vector.lean

* remove the possibility of passing in witness value inputs when running a circuit, and instead use the more general and sound notion that the prover can use any `env: Nat -> F` to determine assignment of values to variables
* modify `SubCircuit` structure to a form which I think will stand the test of time
* prove a larger part of the underlying justification for replacing subcircuits with their specs
* reduce the theorem that allows us to use a `FormalCircuit` as a `SubCircuit` to the equivalence of flattened and nested constraints
* remove lots of (now) obsolete code

[Circuit monad] Proper soundness using env function

---

Clean/Circuit/Circuit.lean

Instead of instantiating subcircuits with a new `Context F` -- which determines the numbering of variables --, we pass the current context down to subcircuits
Thanks to this, in the final list of constraints we now have distinct indices for distinct vars, which seems important

[Circuit monad] Shared context

---

Clean/Circuit/Basic.lean
Clean/Circuit/Expression.lean
Clean/Circuit/Extensions.lean
Clean/Circuit/SubCircuit.lean
Clean/Examples/Gadgets.lean
Clean/GadgetsNew/Add8/Addition8.lean
Clean/GadgetsNew/Add8/Addition8Full.lean
Clean/GadgetsNew/Add8/Addition8FullCarry.lean
Clean/GadgetsNew/Addition32Full.lean
Clean/GadgetsNew/Boolean.lean
Clean/GadgetsNew/ByteLookup.lean
Clean/Types/Byte.lean
Clean/Types/U32.lean

this cleans up `Circuit.Basic`, splits out two additional files whose content isn't "basic", improves some names, and adds some exports so we don't have to open various modules all the time

Circuit cleanup

---

Clean/Circuit/Basic.lean
Clean/Circuit/Provable.lean
Clean/Circuit/SubCircuit.lean
Clean/GadgetsNew/Add8/Addition8FullCarry.lean
Clean/GadgetsNew/Add8/Theorems.lean
Clean/GadgetsNew/Boolean.lean

I wanted to embed the `assert_bool` circuit in our framework but realized it's not a `FormalCircuit`: by design, `assert_bool` is not complete on all inputs - it will of course fail on non-boolean inputs!
This lead me to formulate an alternative called `FormalAssertion` to capture circuits like this. The low-level representation is the same -- `Operation.SubCircuit` - but the structure of hypotheses is slightly different.
To test this addition I also made `assert_bool` a subcircuit inside `add8`. This is done in the last commit and is not strictly necessary -- because assert_bool is so simple there's not much gained from abstracting it. But I think it doesn't hurt either

Formalize assertion-like subcircuits

---

Clean/Circuit/Basic.lean
Clean/Circuit/Expression.lean
Clean/Circuit/Provable.lean
Clean/Circuit/SubCircuit.lean
Clean/Examples/Gadgets.lean
Clean/GadgetsNew/Add8/Addition8.lean
Clean/GadgetsNew/Add8/Addition8Full.lean
Clean/GadgetsNew/Add8/Addition8FullCarry.lean
Clean/GadgetsNew/Add8/Theorems.lean
Clean/GadgetsNew/Addition32Full.lean
Clean/GadgetsNew/Boolean.lean
Clean/GadgetsNew/ByteLookup.lean
Clean/Types/Byte.lean
Clean/Types/U32.lean
Clean/Utils/Vector.lean

closes #37 
* Finishes the theorems that justify replacing subcircuit constraints with their soundness / completeness statements
* Finishes proofs for `Vector`
* => there are no remaining `sorry` proofs in the core lib!
* Prune imports across the project

End to end subcircuit soundness

---

Clean.lean
Clean/Circuit/Basic.lean
Clean/Circuit/Extensions.lean
Clean/Circuit/SubCircuit.lean
Clean/GadgetsNew/Equality.lean
Clean/Table/Basic.lean
Clean/TablesNew/Addition8.lean
Clean/TablesNew/Fibonacci8.lean

- Moved the assignment operation outside of the circuit definition
- Defined a `TableConstraint` Monad that we can use to define constraints over concrete trace "windows", which are partial traces with a given number of columns and rows. For example a constraint that only references the current row has to be defined over a window of height 1. For accessing the next row the window height has to be 2 and so on.
- Defined what it means that the constraints hold over a full trace, by inductively make the table constraints hold over the windows
- Defined two example traces: add8 and Fibonacci8
This PR does not addresses the completeness direction for traces, which is still WIP
This PR also does not address foundational aspects of this construction, namely the allocation of internal variables …

Add support for defining constraints over traces: definition and soundness direction

---

Clean/Circuit/Basic.lean
Clean/Circuit/Extensions.lean
Clean/Circuit/SimpGadget.lean
Clean/Circuit/SubCircuit.lean
Clean/Circuit/Theorems.lean
Clean/Gadgets/Addition32Full.lean
Clean/Gadgets/Addition8/Addition8.lean
Clean/Gadgets/Addition8/Addition8Full.lean
Clean/Gadgets/Addition8/Addition8FullCarry.lean
Clean/Gadgets/Addition8/Theorems.lean
Clean/Gadgets/Boolean.lean
Clean/Gadgets/ByteLookup.lean
Clean/Gadgets/Equality.lean
Clean/Table/Basic.lean
Clean/Table/SimpTable.lean
Clean/Tables/Addition8.lean
Clean/Tables/Fibonacci8.lean
Clean/Types/U32.lean
Clean/Utils/Field.lean
Clean/Utils/Vector.lean

- Add two custom simp sets for gadgets and traces, so that specific theorems are not included in the general-purpose simp set
- Replace most of `simp` with `simp only` in the core theorems

Improve simp sanity

---

Clean.lean
Clean/Gadgets/Addition32/Addition32Full.lean
Clean/Gadgets/Addition32/Theorems.lean
Clean/Gadgets/Addition32Full.lean
Clean/Tables/Fibonacci32.lean
Clean/Types/U32.lean
Clean/Utils/Field.lean

Addresses #53
The general proof technique is the same, but lifted to the integers using `zify`.
Actually, we do not even need to go back to the naturals, as we can lift both the assumptions and the goal to the integers.

Fix 32-bit addition assumptions

---

Clean/Circuit/Basic.lean
Clean/Circuit/SubCircuit.lean
Clean/Table/Basic.lean
Clean/Tables/Addition8.lean
Clean/Tables/Fibonacci32.lean
Clean/Tables/Fibonacci8.lean

This PR removes the ability to require assumptions on the entire table in the `FormalTable` soundness proof. Only an assumption on the number of rows is allowed.
It turns out that this works well for all our currently defined tables. In the `Addition8` table, extra byte lookups have to be added on the inputs. In the fibonacci tables, what used to be an assumption naturally follows from the induction hypothesis, if added to the spec.
No assumptions leads to stronger statements for individual tables, but decreases flexibility somewhat when combining tables. Scenarios could arise where constraints have to be duplicated just because we can't have assumptions on the inputs. If this turns out to be the case it will be easy to add assumptions back in.

Remove formal table assumptions

---

Clean/Gadgets/ByteLookup.lean
Clean/Gadgets/Rotation64/ByteRotationTable.lean
Clean/Gadgets/Rotation64/Rotation64.lean
Clean/Gadgets/Rotation64/Rotation64Bytes.lean
Clean/Gadgets/Rotation64/Theorems.lean
Clean/Types/U32.lean
Clean/Types/U64.lean
Clean/Utils/Field.lean

Add 64-bit rotation over byte limbs

---

Clean/Circuit/Basic.lean
Clean/Circuit/Expression.lean
Clean/Circuit/Extensions.lean
Clean/Circuit/Provable.lean
Clean/Gadgets/Addition32/Addition32Full.lean
Clean/Gadgets/Addition8/Addition8.lean
Clean/Gadgets/Addition8/Addition8Full.lean
Clean/Gadgets/Addition8/Addition8FullCarry.lean
Clean/Gadgets/Boolean.lean
Clean/Gadgets/Equality/U32.lean
Clean/Gadgets/Keccak/ThetaC.lean
Clean/Gadgets/Xor/ByteXorTable.lean
Clean/Gadgets/Xor/Xor64.lean
Clean/Table/Basic.lean
Clean/Tables/Addition8.lean
Clean/Tables/Fibonacci32.lean
Clean/Tables/Fibonacci8.lean
Clean/Types/U32.lean
Clean/Types/U64.lean
Clean/Utils/Vector.lean

This PR adds several ways to preserve the structure of provable types inside proofs, so that we can reason at a high level about types like U32 or U64, and not about their individual field elements (bytes).
Using this, I managed to both significantly simplify the fib32 proof, and to prove soundness of the Keccak 'theta' gadget (with some lower level gaps). clean scales fairly easily to both of these examples now!
* add `ProvableStruct`, a way to specify a `ProvableType` from it's _higher-level components_
* example from `Addition32Full`:
```lean
structure Inputs (F : Type) where
x: U32 F
y: U32 F
carry_in: F
instance : ProvableStruct Inputs where
components := [U32, U32, field]
to_components := fun {x, y, carry_in} => .cons x ( .cons y ( .cons carry_in .nil))
from_components := fun (.cons …
```

Preserve Structure of `ProvableType`s

---

Clean/Circuit/Expression.lean
Clean/Circuit/Extensions.lean
Clean/Circuit/Lawful.lean
Clean/Examples/Add32LawfulCircuit.lean

Small follow-up to #71
Adds a tactic to automatically infer `ConstantLawfulCircuits`, which could be useful for loops where this stronger property is needed

Infer constant lawful circuit

---

Clean/Circuit/Basic.lean
Clean/Circuit/Loops.lean
Clean/Gadgets/Addition32/Addition32Full.lean
Clean/Gadgets/Keccak/Chi.lean
Clean/Gadgets/Keccak/KeccakState.lean
Clean/Gadgets/Keccak/ThetaC.lean
Clean/Gadgets/Keccak/ThetaD.lean
Clean/Gadgets/Keccak/ThetaXor.lean
Clean/Table/Basic.lean
Clean/Tables/Fibonacci32.lean
Clean/Utils/Vector.lean

closes #82 
* add loop construct `Circuit.mapFinRange`, i.e. a `for i=0...n` loop usable in a circuit
* make `mapFinRange` simplify smoothly with `circuit_norm`
* rewrite Chi, ThetaC and ThetaXor to use it

Loop simplification

---

Clean/Circuit/Basic.lean
Clean/Circuit/Lawful.lean
Clean/Circuit/Loops.lean
Clean/Gadgets/ByteDecomposition.lean
Clean/Gadgets/Keccak/KeccakRound.lean
Clean/Gadgets/Keccak/Permutation.lean
Clean/Specs/Keccak256.lean
Clean/Utils/Misc.lean
Clean/Utils/Vector.lean

* keccak permutation circuit, which applies the round function 24 times with different round constants
* foldl loop primitive, which is needed here because we apply the loop body to its own result from the last operation

Keccak permutation and `foldl` loops

---

Clean/Gadgets/And/And8.lean
Clean/Utils/Field.lean

adds a non-trivial lifting lemma:
`(c * x).val = c.val * z` for _some_ `z` implies `(c * x).val = c.val * x.val`
the lemma already implicitly existed as part of the AND8 proof, and now we explicitly call it from there.

Lemma about lifting multiplication to Nat

---

Clean/Circuit/Loops.lean
Clean/Gadgets/Equality.lean
Clean/Tables/Fibonacci32.lean

This finishes a line of work on loops in clean, by adding `Circuit.forEach` which is just `Vector.forM` but simplifies well under `circuit_norm`.
* Refactor the generic equality gadget to use `Circuit.forEach`, mainly to test that everything works as expected
* Remove several theorems in `Loops.lean` that aren't needed for our collection of `Circuit` loops

forEach loop

---

Clean.lean
Clean/Circuit/Basic.lean
Clean/Circuit/Loops.lean
Clean/Circuit/Theorems.lean
Clean/Examples/Add32LawfulCircuit.lean
Clean/Gadgets/Addition32/Addition32Full.lean
Clean/Gadgets/Addition8/Addition8FullCarry.lean
Clean/Gadgets/And/And8.lean
Clean/Gadgets/Bits.lean
Clean/Gadgets/Equality.lean
Clean/Gadgets/Keccak/KeccakRound.lean
Clean/Gadgets/Keccak/Permutation.lean
Clean/Gadgets/Xor/Xor64.lean
Clean/Tables/Fibonacci32.lean
Clean/Tables/Fibonacci8.lean

This PR simplifies the definitions of `constraints_holds`, which had a condition to avoid an extra leading `True` in the statement. It turns out that the condition can be hard to simplify, while the leading `True` is trivial to get rid of by adding `and_true` to the simp set.
* add `and_true` and a few similar lemmas to `circuit_norm`
* remove `and_true` & co from simp invocations where it's no longer needed
* simplify the `Bits` gadget proof
* remove unproved theorem that previously was needed for `Bits`

Remove conditionals in `constraints_hold` definition

---

Clean/Circuit/Basic.lean
Clean/Circuit/Extensions.lean
Clean/Circuit/Provable.lean
Clean/Gadgets/Keccak/AbsorbBlock.lean
Clean/Gadgets/Keccak/KeccakState.lean
Clean/Gadgets/Keccak/Permutation.lean
Clean/Specs/Keccak256.lean
Clean/Table/Basic.lean
Clean/Table/Inductive.lean
Clean/Table/Theorems.lean
Clean/Tables/Fibonacci32Inductive.lean
Clean/Tables/KeccakInductive.lean
Clean/Types/U64.lean
Clean/Utils/Vector.lean

* change `InductiveTable` to allow for an extra user input on every row. this essentially makes the table behave like a `foldl` loop, where the circuit defines how you map `(state, input) => state'`
* adds keccak gadget `AbsorbBlock` which XORs an input block with the state, and applies the permutation
* define an `InductiveTable` for keccak, that uses `AbsorbBlock` on every row to map the state + input block on the current row to the new state on the next row

Keccak table

---

Clean/Gadgets/ByteDecomposition/ByteDecomposition.lean
Clean/Gadgets/ByteDecomposition/Theorems.lean
Clean/Gadgets/Equality.lean
Clean/Gadgets/Rotation64/Rotation64Bits.lean
Clean/Gadgets/Rotation64/Theorems.lean
Clean/Types/U64.lean
Clean/Utils/Field.lean

This PR refactors the byte decomposition gadget, which splits a byte into a low part (the first `offset < 8` bits) and a high part.
* The new version no longer depends on a custom `TwoPowerLookup` for the specific offset, but only uses `ByteLookup`. This comes at no cost, since two byte lookups are enough to prove soundness.
* Add the missing completeness proofs for `ByteDecomposition`, `U64ByteDecomposition` and `U32ByteDecomposition`
* Simplify proofs in `ByteDecomposition.Theorems`

Refactor Byte decomposition and finish proofs

---

Clean.lean
Clean/Gadgets/BLAKE3/Permute.lean

Add BLAKE3 permutation, with the corresponding soundness and completeness proofs ([reference](https://www.ietf.org/archive/id/draft-aumasson-blake3-00.html#name-message-word-permutation))

Add BLAKE3 permutation

---

Clean/Gadgets/BLAKE3/BLAKE3G.lean
Clean/Gadgets/Keccak/AbsorbBlock.lean
Clean/Gadgets/Keccak/KeccakRound.lean
Clean/Gadgets/Keccak/Permutation.lean
Clean/Gadgets/Keccak/RhoPi.lean
Clean/Gadgets/Keccak/Theta.lean
Clean/Gadgets/Keccak/ThetaD.lean
Clean/Gadgets/Rotation32/Rotation32.lean
Clean/Gadgets/Rotation32/Rotation32Bits.lean
Clean/Gadgets/Rotation64/Rotation64.lean
Clean/Gadgets/Rotation64/Rotation64Bits.lean

As the title says -- I didn't like that we copied variables just to make the output of bit rotation gadgets easier to deal with. In fact, the concrete value of a circuit's output rarely matters in parent circuits, and a reasonable strategy to reduce complexity is to wrap the output in a method that parent circuits never have to unfold.
* Abstract away output of bit rotation and general rotation gadgets
* Adapt many hard-coded offsets in Keccak elaborated circuits, since we reduced the number of variables
* Adapt and simplify Blake3 G proof

Get rid of copy constraint in bit rotation gadget

---

Clean/Specs/Keccak256.lean
Clean/Utils/Bitwise.lean
Clean/Utils/Field.lean
Clean/Utils/Misc.lean
Clean/Utils/Vector.lean

I followed outputs of the min_imports command. The changes aim at importing only those Mathlib files that are needed.
I don't know whether we want to optimize imports this way. Caches work well enough?

Lighter Mathlib dependency

---

Clean/Circuit/Basic.lean
Clean/Circuit/Subcircuit.lean
Clean/Gadgets/Bits.lean

I wanted to do this for a while, this covers circuits not properly covered by either assertion or formal circuit, because they're a mix of both. the way to do this is simply not coupling the soundness conclusion (Spec) with the completeness hypothesis (Assumptions) at all.
Note that `GeneralFormalCircuit` is a common generalization of both `FormalCircuit` and `FormalAssertion`, i.e. it could represent a `FormalCircuit` by taking `Spec := Assumptions \r Spec`

General Formal Circuit

---

Clean/Circuit/Basic.lean
Clean/Circuit/Subcircuit.lean
Clean/Gadgets/Addition8/Addition8.lean
Clean/Gadgets/Bits.lean
Clean/Gadgets/Equality.lean
Clean/Gadgets/Keccak/Chi.lean
Clean/Gadgets/Keccak/Theta.lean
Clean/Specs/Keccak256.lean
Clean/Table/Basic.lean
Clean/Table/Inductive.lean
Clean/Table/WitnessGeneration.lean
Clean/Tables/Addition8.lean
Clean/Tables/Fibonacci32.lean
Clean/Tables/Fibonacci8.lean
Clean/Tables/KeccakInductive.lean
Clean/Utils/Bits.lean
Clean/Utils/Rotation.lean
Clean/Utils/Vector.lean

various small things I wanted to clean up:
* rename a few more definitions according to lean conventions
* change the alpha and beta types in formal circuit definition to much clearer `Input` and `Output`
* get rid of `SubcircuitSoundness`, `SubcircuitCompleteness` definitions which were only used in one place and had to be unfolded in every proof
* consistently use `vector[i]` instead of `vector.get i`
* remove changes to the default `simp` set, I feel like we're not supposed to do that given that we maintain our own simp sets already

Some cleanup and renaming

---

Clean/Circuit/Theorems.lean

Following the spirit of `FormalCircuit.isGeneralFormalCircuit`, now I proved that `FormalAssertion` can also be converted into a `GeneralFormalCircuit`.

FormalAssertion.isGeneralFormalCircuit

---

Clean/Circomlib/Comparators.lean
Clean/Circomlib/Mux1.lean
Clean/Circuit/Basic.lean
Clean/Circuit/Explicit.lean
Clean/Circuit/Provable.lean
Clean/Gadgets/ByteDecomposition/ByteDecomposition.lean
Clean/Utils/Misc.lean
Clean/Utils/Vector.lean

* add `Witnessable` type class to improve witnessing of pure `Expression F` and get rid of `witnessField`
* some simplifications here and there

Make witnessing a type class for better inference

---

Clean/Gadgets/BLAKE3/Compress.lean

The `Compress` proofs were using `h_eval : eval env input_var = input` in the right-to-left way. This PR removes the reversal.

Avoid turning input into eval env input_var

---

Clean.lean
Clean/Circuit/Provable.lean
Clean/Circuit/Theorems.lean
Clean/Gadgets/IsZero.lean
Clean/Gadgets/IsZeroField.lean

This will be useful in #229 because `IsZeroU32` can be replaced with the general version in this PR.

IsZero gadget for ProvableType in general

---

Clean/Circomlib/Sign.lean

Added soundness and completeness for the `Sign` circuit in `circomlib`.  Solves #235

Proved soundness and completeness of circomlib/Sign
